-- Add new QuestionType enum values
-- These must be committed in a separate transaction before they can be used
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCHING_HEADINGS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCHING_INFORMATION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCHING_FEATURES';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCHING_SENTENCE_ENDINGS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'SUMMARY_COMPLETION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'NOTE_COMPLETION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'LABELLING';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READ_ALOUD';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'DESCRIBE_PICTURE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'RESPOND_TO_QUESTIONS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'PROPOSE_SOLUTION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'EXPRESS_OPINION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'WRITE_SENTENCES';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'RESPOND_WRITTEN_REQUEST';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'WRITE_OPINION_ESSAY';
