# =============================================================================
# CLOUD SQL MODULE — Managed PostgreSQL
# =============================================================================
# Replaces infra/modules/rds (AWS RDS). Same idea: a managed Postgres server,
# private IP only (§8 open question resolved — see modules/network's header
# comment for why). No public IP, no "authorized networks" list to maintain.
#
# COST NOTE — this is NOT a like-for-like swap of AWS's db.t3.micro:
# ---------------------------------------------------------------------
# AWS RDS has free-tier-eligible shared-core instances (db.t3.micro).
# Cloud SQL for PostgreSQL does NOT support shared-core machine types
# (db-f1-micro/db-g1-small) — those exist for MySQL only. The actual floor
# for Postgres is a custom machine type; "db-custom-1-3840" (1 vCPU, 3.75GB)
# below is the smallest valid, documented option. Expect this to cost more
# per month than the AWS instance did — budget accordingly.
#
# The database password is generated by Terraform (random_password), not
# supplied by you — it never needs to pass through chat or a config file you
# manage by hand. It's stored only in Terraform state (in the access-
# controlled GCS bucket) and surfaced as a sensitive output.
# =============================================================================

terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

resource "random_password" "db_password" {
  length = 32
  # Avoid characters that need escaping/encoding inside a postgres:// URL
  # (DATABASE_URL) — keeps the connection string simple to construct later.
  override_special = "_-"
}

resource "google_sql_database_instance" "postgres" {
  project             = var.project_id
  name                = "${var.project_name}-postgres"
  region              = var.region
  database_version    = "POSTGRES_15"
  deletion_protection = var.deletion_protection

  settings {
    tier              = var.tier
    availability_type = "ZONAL" # single instance, no HA standby — matches the AWS side's single db.t3.micro (no Multi-AZ)
    disk_type         = "PD_SSD"
    disk_size         = 10
    disk_autoresize   = true

    backup_configuration {
      enabled    = true
      start_time = "17:00" # UTC — ~00:00 ICT (Vietnam, UTC+7), a low-traffic window
    }

    ip_configuration {
      ipv4_enabled                                  = false # no public IP at all
      private_network                               = var.vpc_id
      enable_private_path_for_google_cloud_services = true
    }
  }
}

resource "google_sql_database" "app" {
  project  = var.project_id
  name     = var.db_name
  instance = google_sql_database_instance.postgres.name
}

resource "google_sql_user" "app" {
  project  = var.project_id
  name     = var.db_username
  instance = google_sql_database_instance.postgres.name
  password = random_password.db_password.result
}
